### ISSUE TITLE
Rssconnector / Solr broken

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#113]
I can't launch rssconnector to test / document . It seem Solr is broken
Added httpmime-4.5.2 into solr and httpclient but no effect, any idea ? 

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/entity/mime/content/ContentBody
	at org.myrobotlab.service.Solr.startService(Solr.java:249)
	at org.myrobotlab.service.Runtime.createAndStart(Runtime.java:295)
	at org.myrobotlab.service.Runtime.start(Runtime.java:1730)
	at org.myrobotlab.service.RSSConnector.main(RSSConnector.java:96)
Caused by: java.lang.ClassNotFoundException: org.apache.http.entity.mime.content.ContentBody
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

So I tried to add

**Comment by supertick** [comment]
I suspect clashing HttpClient versions
(something probably we could take care of more easily in the future maven build)

**Comment by kwatters** [comment]
We will fix it after the release.  Also update the version of solr.

**Comment by kwatters** [comment]
changing out the "feed4j" library with "rome"

**Comment by kwatters** [comment]
tested in nixie 1.1.104 and it looks good now. closing issue.

**Comment by aroopganguly** [comment]
any solutions to this ?

**Comment by LunDev** [comment]
@aroopganguly 
According to @kwatters this was fixed in April already.
You may want to open a new issue and describe your exact problem there.

**Comment by kwatters** [comment]
This is fixed on the Nixie release when we updated the Ras connector to use the Rome  library.
