### ISSUE TITLE
Testing published jar without -install all

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#238]
The question is do we get all services worky without install all 
or force install all at first launch

Exemple : openWeatherMap=Runtime.start("openWeatherMap", "OpenWeatherMap") crash because dependency issue with httpclient

**Comment by moz4r** [comment]
there is something strange : 

if first I install openweathermap , then install all I get this error.
If install all at the begining, no errors ...

Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:53)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:57)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:47)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:83)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:96)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:105)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:63)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:586)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:180)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:164)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:971)
	at org.apache.http.impl.client.HttpClients.createSystem(HttpClients.java:64)
	at org.myrobotlab.service.HttpClient.startService(HttpClient.java:269)
	at org.myrobotlab.service.Runtime.createAndStart(Runtime.java:246)
	at org.myrobotlab.service.Runtime.start(Runtime.java:1513)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)

**Comment by moz4r** [comment]
removed httpclient import and added json meta dependencies. ok

**Comment by moz4r** [comment]
next : https://github.com/MyRobotLab/myrobotlab/issues/216

**Comment by moz4r** [comment]
ohh seem marytts install break httpclient ...
