### ISSUE TITLE
Raspi + I2C

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#262]
A friend just tell me : NO WORKY, with service script. ( NPE while attach, line 6 )
will try soon, someone use it with nixie ?
https://github.com/MyRobotLab/pyrobotlab/blob/master/service/Adafruit16CServoDriverPi.py

**Comment by moz4r** [comment]
I confirm, something is broken :(

Traceback (most recent call last):
  File "<string>", line 3, in <module>
	at org.myrobotlab.service.RasPi.createI2cDevice(RasPi.java:394)
	at org.myrobotlab.service.RasPi.attachI2CControl(RasPi.java:375)
	at org.myrobotlab.service.Adafruit16CServoDriver.attachI2CController(Adafruit16CServoDriver.java:837)
	at org.myrobotlab.service.Adafruit16CServoDriver.attach(Adafruit16CServoDriver.java:820)
	at org.myrobotlab.service.Adafruit16CServoDriver.attach(Adafruit16CServoDriver.java:805)
	at org.myrobotlab.service.Adafruit16CServoDriver.setController(Adafruit16CServoDriver.java:766)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
java.lang.NullPointerException: java.lang.NullPointerException

	at org.python.core.Py.JavaError(Py.java:552)
	at org.python.core.Py.JavaError(Py.java:543)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:534)
	at org.python.core.PyObject.__call__(PyObject.java:540)
	at org.python.core.PyMethod.__call__(PyMethod.java:171)
	at org.python.pycode._pyx3.f$0(<string>:3)
	at org.python.pycode._pyx3.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	at org.myrobotlab.service.Python$PIThread.run(Python.java:159)
Caused by: java.lang.NullPointerException
	at org.myrobotlab.service.RasPi.createI2cDevice(RasPi.java:394)
	at org.myrobotlab.service.RasPi.attachI2CControl(RasPi.java:375)
	at org.myrobotlab.service.Adafruit16CServoDriver.attachI2CController(Adafruit16CServoDriver.java:837)
	at org.myrobotlab.service.Adafruit16CServoDriver.attach(Adafruit16CServoDriver.java:820)
	at org.myrobotlab.service.Adafruit16CServoDriver.attach(Adafruit16CServoDriver.java:805)
	at org.myrobotlab.service.Adafruit16CServoDriver.setController(Adafruit16CServoDriver.java:766)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	... 12 more

**Comment by moz4r** [comment]
ohh : https://github.com/MyRobotLab/myrobotlab/blob/develop/src/main/java/org/myrobotlab/i2c/I2CFactory.java#L42
