### ISSUE TITLE
Services without UI cause now errors on start

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#273]
23:01:09.959 [AWT-EventQueue-0] ERROR c.m.f.Instantiator [Instantiator.java:21] getNewInstance failed for null org.myrobotlab.swing.AudioFileGui {}
java.lang.ClassNotFoundException: org.myrobotlab.swing.AudioFileGui
	at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[na:1.8.0_181]
	at org.myrobotlab.framework.Instantiator.getThrowableNewInstance(Instantiator.java:38) [myrobotlab.jar:1.1.0]
	at org.myrobotlab.framework.Instantiator.getNewInstance(Instantiator.java:19) [myrobotlab.jar:1.1.0]
	at org.myrobotlab.framework.Instantiator.getNewInstance(Instantiator.java:31) [myrobotlab.jar:1.1.0]
	at org.myrobotlab.service.SwingGui$1.run(SwingGui.java:306) [myrobotlab.jar:1.1.0]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [na:1.8.0_181]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.8.0_181]
	at java.awt.EventQueue.access$500(Unknown Source) [na:1.8.0_181]
	at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_181]
	at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_181]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_181]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.8.0_181]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_181]
	at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_181]

**Comment by supertick** [comment]
Aye its ugly, I probably did it when trying to get more information
about the details of the cast.  closes #273
