### ISSUE TITLE
Yolo memory overflow ( all threaded filters ? )

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#294]
test : ( multiple times )

Worky 1 time / 2, memory increase at every launch of command.
Yolo thread is still running, after filter remove.

opencv.capture()
opencv.removeFilters()
opencv.addFilter("PyramidDown")
opencv.addFilter("Yolo")
sleep(5)
opencv.removeFilters()
opencv.stopCapture()

**Comment by moz4r** [comment]
i01.opencv.capture()
i01.opencv.removeFilters()
i01.opencv.addFilter("PyramidDown")
i01.opencv.addFilter("Yolo")
sleep(5)
i01.opencv.stopCapture()
i01.opencv.removeFilters()

**Comment by moz4r** [comment]
after shutdown : 

21:41:12.967 [i01.opencv] ERROR c.m.f.Service [Service.java:2073] i01.opencv error InvocationTargetException - null java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor67.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.myrobotlab.service.OpenCV.createFrameGrabber(OpenCV.java:491)
	at org.myrobotlab.service.OpenCV.capture(OpenCV.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.myrobotlab.framework.Service.invokeOn(Service.java:1370)
	at org.myrobotlab.framework.Service.invoke(Service.java:1306)
	at org.myrobotlab.framework.Service.run(Service.java:1706)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (7265M) > maxPhysicalBytes (7232M)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:588)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:124)
	at org.bytedeco.javacpp.opencv_core$Mat.allocate(Native Method)
	at org.bytedeco.javacpp.opencv_core$Mat.<init>(opencv_core.java:19261)
	at org.bytedeco.javacv.OpenCVFrameGrabber.<init>(OpenCVFrameGrabber.java:91)
	... 13 more

**Comment by moz4r** [comment]
seem yolo thread still running, after filter removed

**Comment by moz4r** [comment]
opencv.removeFilters() is ok now.
@kwatters if you can find a solution for memory that increase at every launch of filter, it is very welcome !

**Comment by hairygael** [comment]
Hello guys,
I just tried version 1.1.952 with launching openCV. The swinGui window over expended my screen just like it use to do before. :(
Then I tried "face detection" voice command, openCV UI freezed. I have sent a noworky just in case.
:)

**Comment by moz4r** [comment]
Hi Gael, I ear hammer from @GroG forge about openCV polish, a little mishap, someone stole his anvil with code inside

**Comment by moz4r** [comment]
Fresh test on the robot (4gb ram) I can launch only twice the filter, until it overflow memory and crash the system.

**Comment by moz4r** [comment]
1.1.14 testing : 

Wahoo ! no more RAM issue, but this cause runtime random crash, after filter released

[hs_err_pid8684.log](https://github.com/MyRobotLab/myrobotlab/files/2605156/hs_err_pid8684.log)

**Comment by supertick** [comment]
you can use filter.enable()/filter.disable()
there can still be issues caused by invalid states of filters as the pipeline changes.
Its cleaner and less problematic if you load all filters your interested in the pipeline and just enable/disable them at the appropriate time.
