### ISSUE TITLE
Seem openni borked

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#323]
**Describe the bug**
NO WORKY :) . Not done a lot of test for now.

**To Reproduce**
just start openni service

**Desktop (please complete the following information):**
win64

16:23:59.473 [runtime] ERROR c.SimpleOpenNI [SimpleOpenNI.java:103] Can't load SimpleOpenNI library (SimpleOpenNI64.dll) : java.lang.UnsatisfiedLinkError: Can't load library: D:/Nouveaudossier/libraries/native/OpenNI2.dll
16:23:59.474 [runtime] ERROR c.SimpleOpenNI [SimpleOpenNI.java:104] Verify if you installed SimpleOpenNI correctly.
http://code.google.com/p/simple-openni/wiki/Installation
16:23:59.488 [runtime] ERROR c.m.f.Service [Service.java:1443] InvocationTargetException
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_172]
	at org.myrobotlab.framework.Service.invokeOn(Service.java:1375) [myrobotlab.jar:1.1.0]
	at org.myrobotlab.framework.Service.invoke(Service.java:1311) [myrobotlab.jar:1.1.0]
	at org.myrobotlab.framework.Service.run(Service.java:1718) [myrobotlab.jar:1.1.0]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_172]
Caused by: java.lang.UnsatisfiedLinkError: SimpleOpenNI.SimpleOpenNIJNI.swig_module_init()V
	at SimpleOpenNI.SimpleOpenNIJNI.swig_module_init(Native Method) ~[openni-1.96.jar:1.1.0]
	at SimpleOpenNI.SimpleOpenNIJNI.<clinit>(SimpleOpenNIJNI.java:290) ~[openni-1.96.jar:1.1.0]
	at SimpleOpenNI.ContextWrapper.getcwd(ContextWrapper.java:67) ~[openni-1.96.jar:1.1.0]
	at SimpleOpenNI.SimpleOpenNI.start(SimpleOpenNI.java:275) ~[myrobotlab.jar:1.1.0]
	at org.myrobotlab.service.OpenNi.initContext(OpenNi.java:718) ~[myrobotlab.jar:1.1.0]
	at org.myrobotlab.service.OpenNi.startService(OpenNi.java:872) ~[myrobotlab.jar:1.1.0]
	at org.myrobotlab.service.Runtime.createAndStart(Runtime.java:246) ~[myrobotlab.jar:1.1.0]
	... 8 common frames omitted

**Comment by moz4r** [comment]
missing some deps ... will try to add some profiles inside pom.xml
