### ISSUE TITLE
Can't serialize ServoController.

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#370]
**Describe the bug**
 This cause gson loading crash : `HashMap<String, ServoController> controllers = new HashMap<String, ServoController>();`

If I set it to transient it will fix, but no more serialisable. Maybe a deeper fix to push somewhere ? Just wonder if it can break something elsewhere. Also maybe serialisable this hashmap maybe useful.

**To Reproduce**
You can test using load() inside inmoov service

**Screenshots**
```
23:09:36.521 [main] ERROR c.myrobotlab.framework.Service - failed loading C:\Users\moz4r\git\myrobotlab\.myrobotlab\InMoov-i01.json
java.lang.RuntimeException: Unable to invoke no-args constructor for interface org.myrobotlab.service.interfaces.ServoController. Register an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226) ~[gson-2.8.0.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210) ~[gson-2.8.0.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[gson-2.8.0.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.0.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar:na]
	at org.myrobotlab.codec.CodecUtils.fromJson(CodecUtils.java:128) ~[classes/:na]
	at org.myrobotlab.framework.Service.load(Service.java:1577) [classes/:na]
	at org.myrobotlab.framework.Service.load(Service.java:1558) [classes/:na]
	at org.myrobotlab.service.Runtime.loadAndStart(Runtime.java:277) [classes/:na]
	at org.myrobotlab.service.InMoov.main(InMoov.java:1970) [classes/:na]
Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: org.myrobotlab.service.interfaces.ServoController
	at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117) ~[gson-2.8.0.jar:na]
	at com.google.gson.internal.UnsafeAllocator.access$000(UnsafeAllocator.java:31) ~[gson-2.8.0.jar:na]
	at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49) ~[gson-2.8.0.jar:na]
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223) ~[gson-2.8.0.jar:na]
	... 15 common frames omitted
```

**Comment by supertick** [comment]
all services are currently tested by elves in the intertoobs - fixed long ago
