### ISSUE TITLE
MJpegFrameGrabber is borked in the latest

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#371]
Using an installed version of the latest into a clean directory:
I do a full install, then start myrobotlab normally.

I then run the following python code:

from org.myrobotlab.opencv import MJpegFrameGrabber

eyeUrl = "http://10.0.0.19:8080/?action=stream"
opencv = Runtime.start("opencv", "OpenCV")
grabber = MJpegFrameGrabber(eyeUrl)
opencv.capture(grabber)

This should connect to an mjpeg stream running at the above url, however, it fails, and the logs spit out the following message:

21:36:56.117 [python.interpreter.5] INFO  c.m.opencv.MJpegFrameGrabber - Startring MJpeg frame grabber for uri http://10.0.0.19:8080/?action=stream
21:36:56.117 [opencv-video-processor] INFO  class org.myrobotlab.service.OpenCV - beginning capture
21:36:56.117 [opencv-video-processor] INFO  class org.myrobotlab.service.OpenCV - grabber null started - length time 0 length frames 0
21:36:56.117 [opencv-video-processor] ERROR class org.myrobotlab.service.OpenCV - getting grabber failed
java.lang.NullPointerException: null
        at org.myrobotlab.opencv.MJpegFrameGrabber.grab(MJpegFrameGrabber.java:88) ~[myrobotlab.jar:1.1.35]
        at org.myrobotlab.service.OpenCV$VideoProcessor.run(OpenCV.java:162) ~[myrobotlab.jar:1.1.35]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
21:36:56.117 [opencv-video-processor] INFO  c.m.opencv.MJpegFrameGrabber - MJpeg Frame grabber stop called

**Comment by kwatters** [comment]
It would seem that now 
grabber.start()  
does not get called automatically for you... so you have to explicitly start the grabber before you call capture with the grabber, which seems silly.

If you tell opencv to capture with a grabber, it should start the grabber if it's not already started.
