### ISSUE TITLE
InMoov startAll(leftPort, rightPort) fails with null pointer exception.

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#374]
**Describe the bug**
When starting the inmoov service i tell all services to start with a left com port and a right com port.  I subsequently see a null pointer exception in that 

`15:37:25.006 [python.interpreter.16] ERROR c.m.f.Service [Arduino.java:514] serial open threw
java.lang.NullPointerException: null
        at org.myrobotlab.service.Arduino.connect(Arduino.java:469) [myrobotlab.jar:1.1.0]
        at org.myrobotlab.service.Arduino.connect(Arduino.java:449) [myrobotlab.jar:1.1.0]
        at org.myrobotlab.service.InMoovHand.connect(InMoovHand.java:167) [myrobotlab.jar:1.1.0]
        at org.myrobotlab.service.InMoov.startHand(InMoov.java:1234) [myrobotlab.jar:1.1.0]
        at org.myrobotlab.service.InMoov.startRightHand(InMoov.java:1490) [myrobotlab.jar:1.1.0]
        at org.myrobotlab.service.InMoov.startRightHand(InMoov.java:1486) [myrobotlab.jar:1.1.0]
        at org.myrobotlab.service.InMoov.startAll(InMoov.java:1162) [myrobotlab.jar:1.1.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188) [myrobotlab.jar:1.1.0]
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206) [myrobotlab.jar:1.1.0]
        at org.python.core.PyObject.__call__(PyObject.java:515) [myrobotlab.jar:1.1.0]
        at org.python.core.PyObject.__call__(PyObject.java:519) [myrobotlab.jar:1.1.0]
        at org.python.core.PyMethod.__call__(PyMethod.java:156) [myrobotlab.jar:1.1.0]
        at org.python.pycode._pyx16.f$0(<string>:1) [myrobotlab.jar:na]
        at org.python.pycode._pyx16.call_function(<string>) [myrobotlab.jar:na]
        at org.python.core.PyTableCode.call(PyTableCode.java:171) [myrobotlab.jar:1.1.0]
        at org.python.core.PyCode.call(PyCode.java:18) [myrobotlab.jar:1.1.0]
        at org.python.core.Py.runCode(Py.java:1614) [myrobotlab.jar:1.1.0]
        at org.python.core.Py.exec(Py.java:1658) [myrobotlab.jar:1.1.0]
        at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267) [myrobotlab.jar:1.1.0]
        at org.myrobotlab.service.Python$PIThread.run(Python.java:159) [myrobotlab.jar:1.1.0]
15:37:25.053 [python.interpreter.16] ERROR c.m.l.Logging [Logging.java:19] ------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
        at java.util.regex.Matcher.reset(Matcher.java:309)
        at java.util.regex.Matcher.<init>(Matcher.java:229)
        at java.util.regex.Pattern.matcher(Pattern.java:1093)
        at java.util.Formatter.parse(Formatter.java:2547)
        at java.util.Formatter.format(Formatter.java:2501)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at org.myrobotlab.framework.Service.error(Service.java:2128)
        at org.myrobotlab.framework.Service.error(Service.java:2135)
        at org.myrobotlab.service.Arduino.connect(Arduino.java:515)
        at org.myrobotlab.service.Arduino.connect(Arduino.java:449)
        at org.myrobotlab.service.InMoovHand.connect(InMoovHand.java:167)
        at org.myrobotlab.service.InMoov.startHand(InMoov.java:1234)
        at org.myrobotlab.service.InMoov.startRightHand(InMoov.java:1490)
        at org.myrobotlab.service.InMoov.startRightHand(InMoov.java:1486)
        at org.myrobotlab.service.InMoov.startAll(InMoov.java:1162)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
java.lang.NullPointerException: java.lang.NullPointerException

`

**To Reproduce**
download the latest, install all.
start myrobotlab   (java -jar myrobotlab.jar) 
run the following python code

```
leftPort = "/dev/ttyACM0"
rightPort = "/dev/ttyACM1"
i01 = Runtime.createAndStart("i01", "InMoov")
i01.startAll(leftPort, rightPort)
```
**Expected behavior**
All services of the inmoov should start up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: testing on raspi
 - Browser n/a
 - Version latest...

**Additional context**

**Comment by kwatters** [comment]
I think the issue is that the Serial port was null.  (or maybe the port was null..) not sure which it is yet.

**Comment by kwatters** [comment]
no longer seeing this exception.
