### ISSUE TITLE
save predicates throws exception

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#380]
**Describe the bug**
In Gael's log we are seeing an exception where the "savePredicates" call is throwing a FileNotFound exception.  It's possible that the directory it's trying to write to does not exist.  

More info in the log here:  http://myrobotlab.org/myrobotlab_log/upload/hairygael/1543775524.myrobotlab.log

`02:19:18.851 [chatBot] ERROR c.m.f.Service [Service.java:1520] InvocationTargetException
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
	at org.myrobotlab.framework.Service.invokeOn(Service.java:1452) [myrobotlab.jar:1.1.42]
	at org.myrobotlab.framework.Service.invoke(Service.java:1385) [myrobotlab.jar:1.1.42]
	at org.myrobotlab.framework.Service.run(Service.java:1799) [myrobotlab.jar:1.1.42]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_191]
Caused by: java.io.FileNotFoundException: Invalid file path
	at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.8.0_191]
	at java.io.FileWriter.<init>(Unknown Source) ~[na:1.8.0_191]
	at org.myrobotlab.service.ProgramAB.savePredicates(ProgramAB.java:564) ~[myrobotlab.jar:1.1.42]
	... 8 common frames omitted`
**Additional context**

**Comment by kwatters** [comment]
closing this out.  if we see something like this again, we can open a new issue for it.
