### ISSUE TITLE
Undock Tabs from SwingGui Borked

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#440]
**Describe the bug**
Undock tab is borked

**To Reproduce**
1. Start SwingGui
2. Undock tab
3. **BOOM**

Uncaught error fetching image:
java.lang.NullPointerException
	at sun.awt.image.URLImageSource.getConnection(URLImageSource.java:116)
	at sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:126)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

**Expected behavior**
the tab undocked

**Comment by supertick** [comment]
Swing ?  no way
