### ISSUE TITLE
myrobotla.jar 1.1.121 won't install

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#444]
It's been an issue since version 1.1.112, when double clicking myrobotlab.jar, it just doesn't do anything.
Thinking it was maybe related to my java 64bit version being obsolete, but installing java 64bit version 205, doesn't change the problem.
This is going on with two of my Windows 10 PC 64 bit.

When trying to run the START-INMOOV.bat, I am able to see this error before the command prompt shuts down:
Exception in thread "main" java.lang.NoClassDefFoundError: org/atmosphere/wasync/Encoder
        at org.myrobotlab.service.Agent.main(Agent.java:1171)
Caused by: java.lang.ClassNotFoundException: org.atmosphere.wasync.Encoder
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by kwatters** [comment]
I have reproduced the error here also.  
@supertick do you think this is related to any of your check-ins ?  I'm pretty sure when my resourceDir changes when in, that I validated a full download & install all ... and it was working. so I think this happened since then.

**Comment by kwatters** [comment]
Thanks for the bug report!  Grog identified the fix.  the latest should be good again.
