### ISSUE TITLE
VinMoov not launching with error

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#448]
Hello Captains,
Great, version myrobotlab.jar 1.1.125 is now installing! That is fixed.
Testing further with the inmoov-develop, there is a error popping with default virtual inmoov.

Uncaught exception thrown in Thread[jME3 Main,5,main]
AssetNotFoundException: E:\Documents\Myrobotlab\myrobotlab.1.1.124\resource/InMoov/monitor/monitor_back.png (Flipped) (Mipmapped)

The webkitrecognition is not working properly in Chrome:
http://localhost:8888/#/service/i01.ear
Chrome keeps a empty blank page, I have sent a NOWORKY, when this happens.

Also when shutting down MRL, the command prompt is throwing some more errors:

`ERROR class org.myrobotlab.logging.Logging - ------
java.lang.IllegalArgumentException: class javax.swing.JFrame declares multiple JSON fields named state
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
        at com.google.gson.Gson.getAdapter(Gson.java:458)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
        at com.google.gson.Gson.getAdapter(Gson.java:458)
        at com.google.gson.Gson.toJson(Gson.java:696)
        at com.google.gson.Gson.toJson(Gson.java:683)
        at com.google.gson.Gson.toJson(Gson.java:638)
        at com.google.gson.Gson.toJson(Gson.java:618)
        at org.myrobotlab.codec.CodecUtils.toJson(CodecUtils.java:384)
        at org.myrobotlab.framework.Service.save(Service.java:1870)
        at org.myrobotlab.service.Runtime.shutdown(Runtime.java:1498)
        at org.myrobotlab.service.Runtime.shutdown(Runtime.java:1479)
        at org.myrobotlab.service.SwingGui.windowClosing(SwingGui.java:748)
        at java.awt.Window.processWindowEvent(Unknown Source)
        at javax.swing.JFrame.processWindowEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
------

09:43:47.701 [webgui] ERROR class org.myrobotlab.logging.Logging - ------
java.lang.IllegalArgumentException: class javax.swing.JFrame declares multiple JSON fields named state
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
        at com.google.gson.Gson.getAdapter(Gson.java:458)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
        at com.google.gson.Gson.getAdapter(Gson.java:458)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
        at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
        at com.google.gson.Gson.toJson(Gson.java:704)
        at com.google.gson.Gson.toJson(Gson.java:683)
        at com.google.gson.Gson.toJson(Gson.java:638)
        at com.google.gson.Gson.toJson(Gson.java:618)
        at org.myrobotlab.codec.CodecJson.encode(CodecJson.java:35)
        at org.myrobotlab.service.WebGui.broadcast(WebGui.java:323)
        at org.myrobotlab.service.WebGui.preProcessHook(WebGui.java:756)
        at org.myrobotlab.framework.Service.run(Service.java:1826)
        at java.lang.Thread.run(Unknown Source)
------

09:43:48.955 [runtime_outbox_0] ERROR c.m.net.CommunicationManager - could not find service gui to process removeTab from sender runtime - tearing down route
09:43:48.955 [i01.leftHand_outbox_0] ERROR c.m.net.CommunicationManager - could not find service webgui to process onStatus from sender i01.leftHand - tearing down route
09:43:48.955 [runtime_outbox_0] ERROR c.m.net.CommunicationManager - could not find service gui to process onReleased from sender runtime - tearing down route
09:43:48.955 [i01.leftHand_outbox_0] ERROR c.m.net.CommunicationManager - could not find service gui to process onStatus from sender i01.leftHand - tearing down route
09:43:48.955 [runtime_outbox_0] ERROR c.m.net.CommunicationManager - could not find service webgui to process onReleased from sender runtime - tearing down route
09:43:48.956 [i01.leftArm.bicep_outbox_0] ERROR c.m.net.CommunicationManager - could not find service webgui to process onStatus from sender i01.leftArm.bicep - tearing down route
09:43:48.956 [i01.rightArm.rotate_outbox_0] ERROR c.m.net.CommunicationManager - could not find service webgui to process onStatus from sender i01.rightArm.rotate - tearing down route
09:43:48.956 [i01.rightArm.rotate_outbox_0] ERROR c.m.net.CommunicationManager - could not find service gui to process onStatus from sender i01.rightArm.rotate - tearing down route
09:43:48.957 [i01.leftArm.bicep_outbox_0] ERROR c.m.net.CommunicationManager - could not find service gui to process onStatus from sender i01.leftArm.bicep - tearing down route`

**Comment by supertick** [comment]
no longer an issue
